services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Amsterdam
      - WATCHPACK_POLLING=true
      - BACKEND_URL
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
