services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - TZ=Europe/Amsterdam
      - WATCHPACK_POLLING=true
      - BACKEND_URL
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm run build && npm run start"
